AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS SAM template for the "Premier League Crime" serverless back-end.

  '
Parameters:
  AppName:
    Type: String
    Description: Application Name. Used to distinguish resources
  FootballApiKey:
    Type: String
    Description: API Key for the Football Data API.
  StadiumTableName:
    Type: String
    Description: Name of the dynamoDB table.
Globals:
  Function:
    Timeout: 30
Resources:
  CloudWatchAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AppName}-lambda-cloudwatch-access-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: cloudwatch-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            Resource:
            - '*'
      - PolicyName: dynamodb-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${StadiumTableName}
  AWSInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS_Service_Interfaces
      ContentUri: s3://premier-league-crime-app-sam-template/62f6d8c93238fc5e4298f8b54f901569
      CompatibleRuntimes:
      - python3.8
  ApiInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: API_Service_Interfaces
      ContentUri: s3://premier-league-crime-app-sam-template/b1fc39e09697f4472d491e90aa6cf64a
      CompatibleRuntimes:
      - python3.8
  CodeUtilities:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Code_Utilities
      ContentUri: s3://premier-league-crime-app-sam-template/f2e91366f6d2413fd04581ac4874ecc4
      CompatibleRuntimes:
      - python3.8
  ProvisionStadiumLocations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AppName}-provision-stadium-locations
      CodeUri: s3://premier-league-crime-app-sam-template/dbe3a1e1412b65f60d44f966dc8d63eb
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Layers:
      - Ref: AWSInterfaces
      - Ref: ApiInterfaces
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn
      Policies:
      - DynamoDBWritePolicy:
          TableName:
            Ref: StadiumTableName
      Environment:
        Variables:
          API_KEY:
            Ref: FootballApiKey
          DYNAMODB_STADIUM_TABLE_NAME:
            Ref: StadiumTableName
  GetListOfStadiums:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AppName}-get-list-of-stadiums
      CodeUri: s3://premier-league-crime-app-sam-template/ac1314813a48374136cef2d70ef7a637
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10
      Layers:
      - Ref: AWSInterfaces
      - Ref: ApiInterfaces
      - Ref: CodeUtilities
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: StadiumTableName
      Environment:
        Variables:
          DYNAMODB_STADIUM_TABLE_NAME:
            Ref: StadiumTableName
  GetCrimesForStadium:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AppName}-get-crimes-for-stadium
      CodeUri: s3://premier-league-crime-app-sam-template/74b2ee92c7f3f08251662912ab441d01
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Layers:
      - Ref: AWSInterfaces
      - Ref: ApiInterfaces
      - Ref: CodeUtilities
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn
Outputs:
  ProvisionStadiumLocationsArn:
    Description: ARN of Get Data Lambda Function
    Value:
      Fn::GetAtt:
      - ProvisionStadiumLocations
      - Arn
    Export:
      Name:
        Fn::Sub: ${AppName}-provision-stadium-locations-arn
  ProvisionStadiumLocationsFunctionName:
    Description: Name of the "provision-stadium-locations" function
    Value:
      Fn::Sub: ${AppName}-provision-stadium-locations
    Export:
      Name:
        Fn::Sub: ${AppName}-provision-stadium-locations-function-name
  GetListOfStadiumsArn:
    Description: ARN of Get Data Lambda Function
    Value:
      Fn::GetAtt:
      - GetListOfStadiums
      - Arn
    Export:
      Name:
        Fn::Sub: ${AppName}-get-list-of-stadiums-arn
  GetCrimesForStadiumArn:
    Description: ARN of Get Data Lambda Function
    Value:
      Fn::GetAtt:
      - GetCrimesForStadium
      - Arn
    Export:
      Name:
        Fn::Sub: ${AppName}-get-crimes-for-stadium-arn
