AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template for the "Premier League Crime" serverless back-end.


Parameters:
  AppName:
    Type: String
    Description: Application Name. Used to distinguish resources
  FootballApiKey:
    Type: String
    Description: API Key for the Football Data API.
  StadiumTableName:
    Type: String
    Description: Name of the dynamoDB table.

    
Globals:
  Function:
    Timeout: 30

Resources:

  CloudWatchAccessPolicy:
    Type: AWS::IAM:Policy
    Properties:
      PolicyName: CloudWatch-Lambda-Access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource:
              - '*'

  CloudWatchAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-lambda-cloudwatch-access-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - !Ref CloudWatchAccessPolicy

  AWSInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS_Service_Interfaces
      ContentUri: layers/aws_interfaces
      CompatibleRuntimes:
        - python3.8

  ApiInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: API_Service_Interfaces
      ContentUri: layers/api_interfaces
      CompatibleRuntimes:
        - python3.8

  CodeUtilities:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Code_Utilities
      ContentUri: layers/code_utilities
      CompatibleRuntimes:
        - python3.8

  ProvisionStadiumLocations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-provision-stadium-locations"
      CodeUri: lambda_functions/provision_stadium_locations
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn
      Policies:
        - DynamoDBWritePolicy: 
            TableName: !Ref StadiumTableName
      Environment:
        Variables: 
          API_KEY: !Ref FootballApiKey
          DYNAMODB_STADIUM_TABLE_NAME: !Ref StadiumTableName

  GetListOfStadiums:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-get-list-of-stadiums"
      CodeUri: lambda_functions/get_list_of_stadiums
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces
        - !Ref CodeUtilities
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn
      Policies:
        - DynamoDBReadPolicy: 
            TableName: !Ref StadiumTableName
      Environment:
        Variables: 
          DYNAMODB_STADIUM_TABLE_NAME: !Ref StadiumTableName

  GetCrimesForStadium:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-get-crimes-for-stadium"
      CodeUri: lambda_functions/get_crimes_for_stadium
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces
        - !Ref CodeUtilities
      Role:
        Fn::GetAtt: CloudWatchAccessRole.Arn


Outputs:
  ProvisionStadiumLocationsArn:
    Description: ARN of Get Data Lambda Function
    Value: !GetAtt ProvisionStadiumLocations.Arn
    Export:
      Name: !Sub '${AppName}-provision-stadium-locations-arn'

  ProvisionStadiumLocationsFunctionName:
    Description: Name of the "provision-stadium-locations" function
    Value: !Sub "${AppName}-provision-stadium-locations"
    Export:
      Name: !Sub '${AppName}-provision-stadium-locations-function-name'

  GetListOfStadiumsArn:
    Description: ARN of Get Data Lambda Function
    Value: !GetAtt GetListOfStadiums.Arn
    Export:
      Name: !Sub '${AppName}-get-list-of-stadiums-arn'

  GetCrimesForStadiumArn:
    Description: ARN of Get Data Lambda Function
    Value: !GetAtt GetCrimesForStadium.Arn
    Export:
      Name: !Sub '${AppName}-get-crimes-for-stadium-arn'