AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template for the "Premier League Crime" serverless back-end.

Globals:
  Function:
    Timeout: 30

Resources:
  AWSInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS_Service_Interfaces
      ContentUri: layers/aws_interfaces
      CompatibleRuntimes:
        - python3.8

  ApiInterfaces:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: API_Service_Interfaces
      ContentUri: layers/api_interfaces
      CompatibleRuntimes:
        - python3.8

  CodeUtilities:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: API_Service_Interfaces
      ContentUri: layers/code_utilities
      CompatibleRuntimes:
        - python3.8

  GenerateStadiumLocations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/provision_stadium_locations
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces

  GetListOfStadiums:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/get_list_of_stadiums
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces
        - !Ref CodeUtilities

  GetCrimesForStadium:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/get_crimes_for_stadium
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Layers:
        - !Ref AWSInterfaces
        - !Ref ApiInterfaces
        - !Ref CodeUtilities
      Environment:
        Variables: 
          API_KEY: "aee7452b2ba84dadb02437d4f90271c4"

# Outputs:
